spring.application.name=tset-challenge
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:test}
spring.datasource.username=${DATABASE_USERNAME:test}
spring.datasource.password=${DATABASE_PASSWORD:test}
